/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sla.servico.forms;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sla.pecas.NegocioPeca;
import sla.servico.DadosServico;
import sla.servico.NegocioServico;
import sla.servico.Servico;

/**
 *
 * @author Consultor SCA 02
 */
public class FormListarServicos extends javax.swing.JFrame {

    /**
     * Creates new form FormListarServicos
     */
    public FormListarServicos() {
        initComponents();
        setTitle("LISTA DE SERVIÇOS");
        setLocationRelativeTo(null);

        try {
            DefaultTableModel model = (DefaultTableModel) jTableListaServicos.getModel();
            //renomeando os títulos das colunas
            model.setColumnIdentifiers(new Object[]{"Ser_Codigo", "Descrição", "Preco"});
            Servico servico = new Servico();
            NegocioServico b = new NegocioServico();
            servico.setDescricao("");
            ArrayList<Servico> listaTotal = b.listarServico();
            for (Servico listaPeca : listaTotal) {
                model.addRow(new Object[]{listaPeca.getCodServico(), listaPeca.getDescricao(), listaPeca.getPreco()});

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaServicos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonConfirmar = new javax.swing.JButton();
        jRadioButtonAlterarServico = new javax.swing.JRadioButton();
        jRadioButtonRemoverServico = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonFiltroServico = new javax.swing.JButton();
        jTextFieldFiltroServico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableListaServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableListaServicos);

        jLabel1.setText("LISTA DE SERVIÇOS");

        jButtonConfirmar.setText("CONFIRMAR");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonAlterarServico);
        jRadioButtonAlterarServico.setText("ALTERAR SERVIÇO");

        buttonGroup1.add(jRadioButtonRemoverServico);
        jRadioButtonRemoverServico.setText("REMOVER SERVIÇO");

        jLabel2.setText("Selecione a peça e em seguida, informe a ação");

        jButtonFiltroServico.setText("PESQUISAR");
        jButtonFiltroServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltroServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonAlterarServico)
                            .addComponent(jRadioButtonRemoverServico))
                        .addGap(184, 184, 184)
                        .addComponent(jButtonConfirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(0, 53, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldFiltroServico, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFiltroServico))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFiltroServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFiltroServico))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButtonConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jRadioButtonAlterarServico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonRemoverServico)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        // TODO add your handling code here:
        //        int index = jComboBox1.getSelectedIndex();
        //      JOptionPane.showMessageDialog(this, "Index combo " + index + " index tabela " + jTable1.getSelectedRow());
        //    Peca p = this.listaPecas.get(index);
        //  JOptionPane.showMessageDialog(this, p.toString());
        try {
            if (jRadioButtonAlterarServico.isSelected()) {
                FormAlterarServico enviaTexto = new FormAlterarServico();
                enviaTexto.setVisible(true);
                Integer servicoSelecionado = (Integer) jTableListaServicos.getValueAt(jTableListaServicos.getSelectedRow(), 0);
                enviaTexto.RecebejTable(servicoSelecionado);

            }

            if (jRadioButtonRemoverServico.isSelected()) {
                Servico b = new Servico();
                NegocioServico a = new NegocioServico();
                Integer servicoSelecionado = (Integer) jTableListaServicos.getValueAt(jTableListaServicos.getSelectedRow(), 0);
                b.setCodServico(servicoSelecionado);
                a.removerServicoCod(b);

                JOptionPane.showMessageDialog(null, " Serviço removido com sucesso.");
                jTextFieldFiltroServico.setText("");
                DefaultTableModel modelo = (DefaultTableModel) jTableListaServicos.getModel();

                while (modelo.getRowCount() > 0) {
                    modelo.removeRow(0);
                }

                Servico servico = new Servico();

                servico.setDescricao("");
                ArrayList<Servico> listaTotal = a.listarServico();
                for (Servico listaServico : listaTotal) {
                    modelo.addRow(new Object[]{listaServico.getCodServico(), listaServico.getDescricao(), listaServico.getPreco()});

                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonFiltroServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltroServicoActionPerformed

        try {
            //recebendo o modelo existente na jTable
            DefaultTableModel model = (DefaultTableModel) jTableListaServicos.getModel();
            //renomeando os títulos das colunas
            model.setColumnIdentifiers(new Object[]{"Ser_Codigo", "Descrição", "Preco"});
            //Zerando as linhas existentes na tabela padrão
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }
            NegocioServico b = new NegocioServico();
            Servico servicoConsultado = new Servico();
            servicoConsultado.setDescricao(jTextFieldFiltroServico.getText());
            ArrayList<Servico> listaServicos = b.consultarServico(servicoConsultado);
            for (Servico listaServico : listaServicos) {
                model.addRow(new Object[]{listaServico.getCodServico(), listaServico.getDescricao(), listaServico.getPreco()});

            }

        } catch (Exception e) {

            try {

                JOptionPane.showMessageDialog(null, e.getMessage());
                //Preenchendo a lista..
                Servico servico = new Servico();
                NegocioServico b = new NegocioServico();
                DefaultTableModel modelo = (DefaultTableModel) jTableListaServicos.getModel();

                servico.setDescricao("");
                ArrayList<Servico> listaTotal = b.listarServico();

                for (Servico listaServico : listaTotal) {
                    modelo.addRow(new Object[]{listaServico.getCodServico(), listaServico.getDescricao(), listaServico.getPreco()});
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, e.getMessage());
                jTextFieldFiltroServico.setText("");
                jTextFieldFiltroServico.requestFocus();
            }

        }

    }//GEN-LAST:event_jButtonFiltroServicoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormListarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormListarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormListarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormListarServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormListarServicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonFiltroServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonAlterarServico;
    private javax.swing.JRadioButton jRadioButtonRemoverServico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaServicos;
    private javax.swing.JTextField jTextFieldFiltroServico;
    // End of variables declaration//GEN-END:variables
}
