/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sla.servico.forms;

import com.microsoft.sqlserver.jdbc.SQLServerException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sla.operacoes.Operacao;
import sla.pecas.NegocioPeca;
import sla.servico.DadosServico;
import sla.servico.NegocioServico;
import sla.servico.Servico;

/**
 *
 * @author Consultor SCA 02
 */
public class FormCadastrarServico extends javax.swing.JFrame {

    /**
     * Creates new form FormCadastrarPeca
     */
    public FormCadastrarServico() {
        initComponents();
        setTitle("CADASTRO DE SERVIÇOS");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelNomeServico = new javax.swing.JLabel();
        jLabelValorServico = new javax.swing.JLabel();
        jTextFieldnomeServico = new javax.swing.JTextField();
        jTextFieldprecoServico = new javax.swing.JTextField();
        jButtonCadastrarServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CADASTRO DE SERVIÇOS");

        jLabelNomeServico.setText("NOME DO SERVIÇO");

        jLabelValorServico.setText("VALOR DO SERVIÇO");

        jButtonCadastrarServico.setText("CADASTRAR SERVIÇO");
        jButtonCadastrarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabelNomeServico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelValorServico)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextFieldnomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jTextFieldprecoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButtonCadastrarServico)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeServico)
                    .addComponent(jLabelValorServico))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldnomeServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldprecoServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButtonCadastrarServico)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarServicoActionPerformed
        try {
            //        if ((jTextFieldnomePeca.getText().trim().isEmpty() && jTextFieldprecoPeca.getText().trim().isEmpty()) == false) {
            //          Peca peca = new Peca();
            //        peca.setDescricao(jTextFieldnomePeca.getText());
            //      peca.setPreco(Float.parseFloat(jTextFieldprecoPeca.getText()));
            //    DadosPeca a = new DadosPeca();
            //jTextFieldnomePeca.setText("");
            //  jTextFieldprecoPeca.setText("");
            // a.cadastrarPeca(peca);
            //     JOptionPane.showMessageDialog(null, "Peça cadastrada com sucesso");
            //       jTextFieldnomePeca.requestFocus();
            //     }
            Servico servico = new Servico();
            Operacao op = new Operacao();
            NegocioServico negocio = new NegocioServico();
            servico.setDescricao(jTextFieldnomeServico.getText());
            String textoPreco = jTextFieldprecoServico.getText();
            if (textoPreco.length() > Float.MAX_VALUE) {
                JOptionPane.showMessageDialog(null, "Preço informado estoura a capacidade de armazenamento da variável.");
                jTextFieldprecoServico.setText("");
                jTextFieldprecoServico.requestFocus();
            }
            Float preco = op.formatadorVirgulaParaPonto(textoPreco);
            servico.setPreco(preco);
            negocio.cadastrarServico(servico);

            JOptionPane.showMessageDialog(null, "Serviço cadastrado com sucesso");
            jTextFieldnomeServico.setText("");
            jTextFieldprecoServico.setText("");
            jTextFieldnomeServico.requestFocus();

        }  catch (NumberFormatException e) {

            // Validação de NumberFormat quando o usuário deixar os 2 campos em branco. 
            // Ele vai entrar no catch por não conseguir converter a variável preco com o método formatadorVirgulaParaPonto, que retorna uma conversão de tipos.
            if (jTextFieldnomeServico.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Informe o nome do servico.");
                jTextFieldnomeServico.requestFocus();
            } else {
                try {
                    Servico servico = new Servico();
                    servico.setDescricao(jTextFieldnomeServico.getText());
                    NegocioServico validaServico = new NegocioServico();
                    validaServico.cadastrarServico(servico);

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                    jTextFieldprecoServico.setText("");
                    jTextFieldprecoServico.requestFocus();
                }

            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e.getMessage());
            jTextFieldprecoServico.setText("");
            jTextFieldprecoServico.requestFocus();
        }

    }//GEN-LAST:event_jButtonCadastrarServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarServico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastrarServico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNomeServico;
    private javax.swing.JLabel jLabelValorServico;
    private javax.swing.JTextField jTextFieldnomeServico;
    private javax.swing.JTextField jTextFieldprecoServico;
    // End of variables declaration//GEN-END:variables
}
