
package sla.clientes.forms;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import sla.clientes.ClientePessoaFisica;
import sla.clientes.ClientePessoaJuridica;
import sla.clientes.NegocioCliente;
import sla.operacoes.Operacao;

/**
 *
 * @author Consultor SCA 02
 */
public class FormAlterarCliente extends javax.swing.JFrame {

    ClientePessoaFisica pf;
    ClientePessoaJuridica pj;
    MaskFormatter mascaraCPF;
    MaskFormatter mascaraCNPJ;
    String textoCpf;
    String textoNome;
    String textoCNPJ;
    String razaoSocial;
    String textoTelefone;
    String textoCEP;
    String logradouro;
    String numeroLogradouro;
    String complemento;
    String bairro;
    String cidade;
    String estado;
    String email;

    /**
     * Creates new form FormAlterarCliente
     */
    public FormAlterarCliente() {
        initComponents();

        try {

            jTextFieldCodCliente.setEnabled(false);
            jTextFieldCpfCnpj.setEnabled(false);
            jTextFieldNomeRazaoSocial.setEnabled(false);
            jTextFieldTelefone.setEnabled(false);
            jTextFieldCep.setEnabled(false);
            jTextFieldEndereco.setEnabled(false);
            jTextFieldNumeroEndereco.setEnabled(false);
            jTextFieldComplemento.setEnabled(false);
            jTextFieldBairro.setEnabled(false);
            jTextFieldCidade.setEnabled(false);
            jTextFieldUF.setEnabled(false);
            jTextFieldEmail.setEnabled(false);
            jTextFieldSexo.setEnabled(false);
            mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraCNPJ = new MaskFormatter("##.###.###/####-##");
            //RecebeJtablePJ(69);
            //mascaracep = new MaskFormatter("##.###-###");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelcomplemento = new javax.swing.JLabel();
        jLabelbairro = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        jLabelOperacaoCpfCNPJ = new javax.swing.JLabel();
        jLabelOperacaoNomeRazaoSocial = new javax.swing.JLabel();
        jLabeltelefoneCliente = new javax.swing.JLabel();
        jLabelenderecoCliente = new javax.swing.JLabel();
        jLabelSexoCliente = new javax.swing.JLabel();
        jLabelcepCliente = new javax.swing.JLabel();
        jLabelcidade = new javax.swing.JLabel();
        jLabelnumeroEndereco = new javax.swing.JLabel();
        jLabel1UF = new javax.swing.JLabel();
        jTextFieldNumeroEndereco = new javax.swing.JTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldUF = new javax.swing.JTextField();
        jTextFieldCep = new javax.swing.JTextField();
        jTextFieldEndereco = new javax.swing.JTextField();
        jTextFieldSexo = new javax.swing.JTextField();
        jTextFieldNomeRazaoSocial = new javax.swing.JTextField();
        jTextFieldCpfCnpj = new javax.swing.JTextField();
        jTextFieldTelefone = new javax.swing.JTextField();
        jLabelMensagemInicial = new javax.swing.JLabel();
        jFormattedTextFieldOperacaoNovoCpfCnpj = new javax.swing.JFormattedTextField();
        jTextFieldNovouf = new javax.swing.JTextField();
        jLabelEXUF = new javax.swing.JLabel();
        jTextFieldNovobairro = new javax.swing.JTextField();
        jTextFieldNovoemail = new javax.swing.JTextField();
        jTextFieldNovocidade = new javax.swing.JTextField();
        jTextFieldOperacaoNovoNomeRazaoSocial = new javax.swing.JTextField();
        jFormattedTextFieldNovotelefoneCliente = new javax.swing.JFormattedTextField();
        jTextFieldNovoEnderecoCliente = new javax.swing.JTextField();
        jTextFieldNovonumeroEndereco = new javax.swing.JTextField();
        jTextFieldNovocomplemento = new javax.swing.JTextField();
        jButtonAtualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodCliente = new javax.swing.JTextField();
        jFormattedTextFieldNovocepCliente = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelcomplemento.setText("COMPLEMENTO");

        jLabelbairro.setText("BAIRRO");

        jLabelemail.setText("EMAIL");

        jLabelOperacaoCpfCNPJ.setText("CPF");

        jLabelOperacaoNomeRazaoSocial.setText("NOME");

        jLabeltelefoneCliente.setText("TELEFONE");

        jLabelenderecoCliente.setText("ENDEREÇO");

        jLabelSexoCliente.setText("SEXO");

        jLabelcepCliente.setText("CEP");

        jLabelcidade.setText("CIDADE");

        jLabelnumeroEndereco.setText("NUMERO");

        jLabel1UF.setText("UF");

        jLabelMensagemInicial.setText("PREENCHA APENAS OS CAMPOS QUE DEVEM SER ATUALIZADOS");

        jTextFieldNovouf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldNovoufKeyTyped(evt);
            }
        });

        jLabelEXUF.setText("Ex: SP");

        try {
            jFormattedTextFieldNovotelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldNovotelefoneCliente.setText("(  )9.    -    ");

        jButtonAtualizar.setText("ATUALIZAR");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        jLabel2.setText("COD");

        jFormattedTextFieldNovocepCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldNovocepClienteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelcepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelenderecoCliente)
                                .addComponent(jLabeltelefoneCliente)
                                .addComponent(jLabelbairro)
                                .addComponent(jLabelemail)
                                .addComponent(jLabelnumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSexoCliente)
                                .addComponent(jLabel1UF)
                                .addComponent(jLabelcomplemento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelcidade)
                                .addComponent(jLabelOperacaoNomeRazaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(jButtonAtualizar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldUF, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextFieldNomeRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jTextFieldCep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                        .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.Alignment.LEADING))
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jTextFieldCodCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                                        .addComponent(jTextFieldCpfCnpj, javax.swing.GroupLayout.Alignment.LEADING)))
                                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNovoemail)
                                    .addComponent(jTextFieldNovoEnderecoCliente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextFieldNovocomplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                .addComponent(jTextFieldNovonumeroEndereco)
                                                .addComponent(jTextFieldNovobairro, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jFormattedTextFieldNovotelefoneCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldNovouf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelEXUF))
                                            .addComponent(jTextFieldOperacaoNovoNomeRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNovocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldOperacaoNovoCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldNovocepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 53, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelOperacaoCpfCNPJ))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(242, 242, 242)
                                .addComponent(jLabelMensagemInicial)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMensagemInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOperacaoCpfCNPJ)
                    .addComponent(jTextFieldCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldOperacaoNovoCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOperacaoNovoNomeRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOperacaoNomeRazaoSocial))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltelefoneCliente)
                    .addComponent(jFormattedTextFieldNovotelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcepCliente)
                    .addComponent(jFormattedTextFieldNovocepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelenderecoCliente)
                    .addComponent(jTextFieldEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNovoEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnumeroEndereco)
                    .addComponent(jTextFieldNumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNovonumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelcomplemento)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNovocomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelbairro)
                        .addComponent(jTextFieldNovobairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelcidade)
                        .addComponent(jTextFieldNovocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1UF)
                    .addComponent(jTextFieldUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNovouf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEXUF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelemail)
                        .addComponent(jTextFieldNovoemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSexoCliente)
                        .addComponent(jTextFieldSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNovoufKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNovoufKeyTyped
        // Teste de uso de eventos para limitar o campo estado somente com caracteres e com limite de 2 caracteres para o estado.
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c)) || c == ' ') {
            evt.consume();
        }
        int numerocaracter = 2;

        if (jTextFieldNovouf.getText().length() >= numerocaracter) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldNovoufKeyTyped

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        NegocioCliente cliente = new NegocioCliente();
        Operacao op = new Operacao();

        if (jLabelOperacaoCpfCNPJ.getText().equals("CPF")) {
            try {
                pf = new ClientePessoaFisica();
                pf.setCli_Codigo(Integer.parseInt(jTextFieldCodCliente.getText()));
                pf.setCli_Cpf(jTextFieldCpfCnpj.getText());
                pf.setNome(jTextFieldNomeRazaoSocial.getText());
                pf.setTelefone(jTextFieldTelefone.getText());
                pf.setCep(jTextFieldCep.getText());
                pf.setLogradouro(jTextFieldEndereco.getText());
                pf.setNumeroLogradouro(jTextFieldNumeroEndereco.getText());
                pf.setComplemento(jTextFieldComplemento.getText());
                pf.setBairro(jTextFieldBairro.getText());
                pf.setCidade(jTextFieldCidade.getText());
                pf.setEstado(jTextFieldUF.getText());
                pf.setEmail(jTextFieldEmail.getText());
                pf.setSexo(jTextFieldSexo.getText());

                textoCpf = jFormattedTextFieldOperacaoNovoCpfCnpj.getText().trim();
                if (textoCpf.charAt(0) != '.') {
                    pf.setCli_Cpf(jFormattedTextFieldOperacaoNovoCpfCnpj.getText());
                }
                textoNome = jTextFieldOperacaoNovoNomeRazaoSocial.getText().trim();
                if (textoNome.isEmpty() == false) {
                    pf.setNome(jTextFieldOperacaoNovoNomeRazaoSocial.getText());
                }

                textoTelefone = jFormattedTextFieldNovotelefoneCliente.getText();
                if (textoTelefone.charAt(1) != ' ') {
                    pf.setTelefone(jFormattedTextFieldNovotelefoneCliente.getText());
                }

                try {
                    textoCEP = jFormattedTextFieldNovocepCliente.getText();
                    if (textoCEP != null && textoCEP.length() == 8) {
                        textoCEP = op.formataCEP(jFormattedTextFieldNovocepCliente.getText());
                        pf.setCep(textoCEP);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }

                logradouro = jTextFieldNovoEnderecoCliente.getText();
                if (logradouro != null && logradouro.isEmpty() == false) {
                    pf.setLogradouro(jTextFieldNovoEnderecoCliente.getText().trim());
                }
                numeroLogradouro = jTextFieldNovonumeroEndereco.getText();
                if (numeroLogradouro != null && numeroLogradouro.isEmpty() == false) {
                    pf.setNumeroLogradouro(numeroLogradouro.trim());
                }
                complemento = jTextFieldNovocomplemento.getText();
                if (complemento != null && complemento.isEmpty() == false) {
                    pf.setComplemento(complemento.trim());
                }
                bairro = jTextFieldNovobairro.getText();
                if (bairro != null && bairro.isEmpty() == false) {
                    pf.setBairro(bairro.trim());
                }
                cidade = jTextFieldNovocidade.getText();
                if (cidade != null && cidade.isEmpty() == false) {
                    pf.setCidade(cidade.trim());
                }
                estado = jTextFieldNovouf.getText();
                if (estado != null && estado.isEmpty() == false) {
                    pf.setEstado(estado.trim());
                }
                email = jTextFieldNovoemail.getText();
                if (email != null && email.isEmpty() == false) {
                    pf.setEmail(email.trim());
                }
                try {
                    cliente.alterarClientePF(pf);
                    jTextFieldCodCliente.setText(String.valueOf(pf.getCli_Codigo()));
                    jTextFieldCpfCnpj.setText(pf.getCli_Cpf());
                    jTextFieldNomeRazaoSocial.setText(pf.getNome());
                    jTextFieldTelefone.setText(pf.getTelefone());
                    jTextFieldCep.setText(pf.getCep());
                    jTextFieldEndereco.setText(pf.getLogradouro());
                    jTextFieldNumeroEndereco.setText(pf.getNumeroLogradouro());
                    jTextFieldComplemento.setText(pf.getComplemento());
                    jTextFieldBairro.setText(pf.getBairro());
                    jTextFieldCidade.setText(pf.getCidade());
                    jTextFieldUF.setText(pf.getEstado());
                    jTextFieldEmail.setText(pf.getEmail());
                    jTextFieldSexo.setText(pf.getSexo());
                    JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso.");
                    jFormattedTextFieldOperacaoNovoCpfCnpj.setText("");
                    jTextFieldOperacaoNovoNomeRazaoSocial.setText("");
                    jFormattedTextFieldNovotelefoneCliente.setText("");
                    jFormattedTextFieldNovocepCliente.setText("");
                    jTextFieldNovoEnderecoCliente.setText("");
                    jTextFieldNovonumeroEndereco.setText("");
                    jTextFieldNovocomplemento.setText("");
                    jTextFieldNovobairro.setText("");
                    jTextFieldNovocidade.setText("");
                    jTextFieldNovouf.setText("");
                    jTextFieldNovoemail.setText("");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                    jFormattedTextFieldOperacaoNovoCpfCnpj.setText("");
                    jTextFieldOperacaoNovoNomeRazaoSocial.setText("");
                    jFormattedTextFieldNovotelefoneCliente.setText("");
                    jFormattedTextFieldNovocepCliente.setText("");
                    jTextFieldNovoEnderecoCliente.setText("");
                    jTextFieldNovonumeroEndereco.setText("");
                    jTextFieldNovocomplemento.setText("");
                    jTextFieldNovobairro.setText("");
                    jTextFieldNovocidade.setText("");
                    jTextFieldNovouf.setText("");
                    jTextFieldNovoemail.setText("");
                }

            } catch (NullPointerException ez) {
                //Possibilidade de tratamento de fluxo de exceções para cada campo nulo específico, pois os campos 
                //foram declarados como variáveis globais.
                if (textoCpf == null) {
                    JOptionPane.showMessageDialog(null, " Valor nulo para o cpf informado. Preencha o campo e tente novamente");
                }

            }

        }
        if (jLabelOperacaoCpfCNPJ.getText().equals("CNPJ")) {
            try {
                pj = new ClientePessoaJuridica();
                pj.setCli_Codigo(Integer.parseInt(jTextFieldCodCliente.getText()));
                pj.setCli_Cnpj(jTextFieldCpfCnpj.getText());
                pj.setRazaoSocial(jTextFieldNomeRazaoSocial.getText());
                pj.setTelefone(jTextFieldTelefone.getText());
                pj.setCep(jTextFieldCep.getText());
                pj.setLogradouro(jTextFieldEndereco.getText());
                pj.setNumeroLogradouro(jTextFieldNumeroEndereco.getText());
                pj.setComplemento(jTextFieldComplemento.getText());
                pj.setBairro(jTextFieldBairro.getText());
                pj.setCidade(jTextFieldCidade.getText());
                pj.setEstado(jTextFieldUF.getText());
                pj.setEmail(jTextFieldEmail.getText());

                textoCNPJ = jFormattedTextFieldOperacaoNovoCpfCnpj.getText();
                if (textoCNPJ.charAt(0) != ' ') {
                    pj.setCli_Cnpj(textoCNPJ);
                }
                razaoSocial = jTextFieldOperacaoNovoNomeRazaoSocial.getText();
                if (razaoSocial != null && razaoSocial.isEmpty() == false) {
                    pj.setRazaoSocial(razaoSocial.trim());
                }
                textoTelefone = jFormattedTextFieldNovotelefoneCliente.getText();
                if (textoTelefone.charAt(1) != ' ') {
                    pj.setTelefone(jFormattedTextFieldNovotelefoneCliente.getText());
                }
                try {
                    textoCEP = jFormattedTextFieldNovocepCliente.getText();
                    if (textoCEP != null && textoCEP.length() == 8) {
                        textoCEP = op.formataCEP(textoCEP);
                        pj.setCep(textoCEP);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                }
                logradouro = jTextFieldNovoEnderecoCliente.getText();
                if (logradouro != null && logradouro.isEmpty() == false) {
                    pj.setLogradouro(jTextFieldNovoEnderecoCliente.getText().trim());
                }
                numeroLogradouro = jTextFieldNovonumeroEndereco.getText();
                if (numeroLogradouro != null && numeroLogradouro.isEmpty() == false) {
                    pj.setNumeroLogradouro(numeroLogradouro.trim());
                }
                complemento = jTextFieldNovocomplemento.getText();
                if (complemento != null && complemento.isEmpty() == false) {
                    pj.setComplemento(complemento.trim());
                }
                bairro = jTextFieldNovobairro.getText();
                if (bairro != null && bairro.isEmpty() == false) {
                    pj.setBairro(bairro.trim());
                }
                cidade = jTextFieldNovocidade.getText();
                if (cidade != null && cidade.isEmpty() == false) {
                    pj.setCidade(cidade.trim());
                }
                estado = jTextFieldNovouf.getText();
                if (estado != null && estado.isEmpty() == false) {
                    pj.setEstado(estado.trim());
                }
                email = jTextFieldNovoemail.getText();
                if (email != null && email.isEmpty() == false) {
                    pj.setEmail(email.trim());
                }
                try {
                    cliente.alterarClientePJ(pj);
                    jTextFieldCodCliente.setText(String.valueOf(pj.getCli_Codigo()));
                    jTextFieldCpfCnpj.setText(pj.getCli_Cnpj());
                    jTextFieldNomeRazaoSocial.setText(pj.getRazaoSocial());
                    jTextFieldTelefone.setText(pj.getTelefone());
                    jTextFieldCep.setText(pj.getCep());
                    jTextFieldEndereco.setText(pj.getLogradouro());
                    jTextFieldNumeroEndereco.setText(pj.getNumeroLogradouro());
                    jTextFieldComplemento.setText(pj.getComplemento());
                    jTextFieldBairro.setText(pj.getBairro());
                    jTextFieldCidade.setText(pj.getCidade());
                    jTextFieldUF.setText(pj.getEstado());
                    jTextFieldEmail.setText(pj.getEmail());
                    JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso.");
                    jFormattedTextFieldOperacaoNovoCpfCnpj.setText("");
                    jTextFieldOperacaoNovoNomeRazaoSocial.setText("");
                    jFormattedTextFieldNovotelefoneCliente.setText("");
                    jFormattedTextFieldNovocepCliente.setText("");
                    jTextFieldNovoEnderecoCliente.setText("");
                    jTextFieldNovonumeroEndereco.setText("");
                    jTextFieldNovocomplemento.setText("");
                    jTextFieldNovobairro.setText("");
                    jTextFieldNovocidade.setText("");
                    jTextFieldNovouf.setText("");
                    jTextFieldNovoemail.setText("");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e.getMessage());
                    jFormattedTextFieldOperacaoNovoCpfCnpj.setText("");
                    jTextFieldOperacaoNovoNomeRazaoSocial.setText("");
                    jFormattedTextFieldNovotelefoneCliente.setText("");
                    jFormattedTextFieldNovocepCliente.setText("");
                    jTextFieldNovoEnderecoCliente.setText("");
                    jTextFieldNovonumeroEndereco.setText("");
                    jTextFieldNovocomplemento.setText("");
                    jTextFieldNovobairro.setText("");
                    jTextFieldNovocidade.setText("");
                    jTextFieldNovouf.setText("");
                    jTextFieldNovoemail.setText("");
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());

                jFormattedTextFieldOperacaoNovoCpfCnpj.setText("");
                jTextFieldOperacaoNovoNomeRazaoSocial.setText("");
                jFormattedTextFieldNovotelefoneCliente.setText("");
                jFormattedTextFieldNovocepCliente.setText("");
                jTextFieldNovoEnderecoCliente.setText("");
                jTextFieldNovonumeroEndereco.setText("");
                jTextFieldNovocomplemento.setText("");
                jTextFieldNovobairro.setText("");
                jTextFieldNovocidade.setText("");
                jTextFieldNovouf.setText("");
                jTextFieldNovoemail.setText("");
            }

        }


    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jFormattedTextFieldNovocepClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldNovocepClienteKeyTyped
        // Teste de uso de eventos para limitar o campo estado somente com caracteres e com limite de 2 caracteres para o estado.
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c))) {
            evt.consume();
        }
        int numerocaracter = 8;

        if (jFormattedTextFieldNovocepCliente.getText().length() >= numerocaracter) {
            evt.consume();
        }
    }//GEN-LAST:event_jFormattedTextFieldNovocepClienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAlterarCliente().setVisible(true);
            }
        });
    }

    public void RecebeJtablePF(Integer pfSelecionado) throws Exception {
        //Alimentando o objeto passado pelo form
        setTitle("ATUALIZAÇÃO DE CLIENTES- PESSOA FISICA");
        pf = new ClientePessoaFisica();
        NegocioCliente a = new NegocioCliente();
        pf.setCli_Codigo(pfSelecionado);
        ArrayList<ClientePessoaFisica> pfConsultado = a.consultarClientePF(pf);
        pf = pfConsultado.get(0);
        //Preenchendo os campos de texto com o objeto alimentado
        jTextFieldCodCliente.setText(String.valueOf(pf.getCli_Codigo()));
        jTextFieldCpfCnpj.setText(pf.getCli_Cpf());
        jTextFieldNomeRazaoSocial.setText(pf.getNome());
        jTextFieldTelefone.setText(pf.getTelefone());
        jTextFieldCep.setText(pf.getCep());
        jTextFieldEndereco.setText(pf.getLogradouro());
        jTextFieldNumeroEndereco.setText(pf.getNumeroLogradouro());
        jTextFieldComplemento.setText(pf.getComplemento());
        jTextFieldBairro.setText(pf.getBairro());
        jTextFieldCidade.setText(pf.getCidade());
        jTextFieldUF.setText(pf.getEstado());
        jTextFieldEmail.setText(pf.getEmail());
        jTextFieldSexo.setText(pf.getSexo());
        //  mascaracep.install(jFormattedTextFieldNovocepCliente);
        mascaraCNPJ.uninstall();
        mascaraCPF.install(jFormattedTextFieldOperacaoNovoCpfCnpj);
    }

    public void RecebeJtablePJ(Integer pjSelecionado) throws Exception {
        setTitle("ATUALIZAÇÃO DE CLIENTES- PESSOA JURIDICA");
        //Alimentando o objeto passado pelo form
        pj = new ClientePessoaJuridica();
        NegocioCliente a = new NegocioCliente();
        pj.setCli_Codigo(pjSelecionado);
        ArrayList<ClientePessoaJuridica> pjConsultado = a.consultarClientePJ(pj);
        pj = pjConsultado.get(0);
        //Preenchendo os campos de texto com o objeto alimentado
        jLabelOperacaoCpfCNPJ.setText("CNPJ");
        jLabelOperacaoNomeRazaoSocial.setText("Razão Social");
        jLabelSexoCliente.setVisible(false);
        jTextFieldSexo.setVisible(false);
        jTextFieldCodCliente.setText(String.valueOf(pj.getCli_Codigo()));
        jTextFieldCpfCnpj.setText(pj.getCli_Cnpj());
        jTextFieldNomeRazaoSocial.setText(pj.getRazaoSocial());
        jTextFieldTelefone.setText(pj.getTelefone());
        jTextFieldCep.setText(pj.getCep());
        jTextFieldEndereco.setText(pj.getLogradouro());
        jTextFieldNumeroEndereco.setText(pj.getNumeroLogradouro());
        jTextFieldComplemento.setText(pj.getComplemento());
        jTextFieldBairro.setText(pj.getBairro());
        jTextFieldCidade.setText(pj.getCidade());
        jTextFieldUF.setText(pj.getEstado());
        jTextFieldEmail.setText(pj.getEmail());
        // mascaracep.install(jFormattedTextFieldNovocepCliente);
        mascaraCPF.uninstall();
        mascaraCNPJ.install(jFormattedTextFieldOperacaoNovoCpfCnpj);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JFormattedTextField jFormattedTextFieldNovocepCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldNovotelefoneCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldOperacaoNovoCpfCnpj;
    private javax.swing.JLabel jLabel1UF;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEXUF;
    private javax.swing.JLabel jLabelMensagemInicial;
    private javax.swing.JLabel jLabelOperacaoCpfCNPJ;
    private javax.swing.JLabel jLabelOperacaoNomeRazaoSocial;
    private javax.swing.JLabel jLabelSexoCliente;
    private javax.swing.JLabel jLabelbairro;
    private javax.swing.JLabel jLabelcepCliente;
    private javax.swing.JLabel jLabelcidade;
    private javax.swing.JLabel jLabelcomplemento;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelenderecoCliente;
    private javax.swing.JLabel jLabelnumeroEndereco;
    private javax.swing.JLabel jLabeltelefoneCliente;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCep;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldCodCliente;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldCpfCnpj;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldNomeRazaoSocial;
    private javax.swing.JTextField jTextFieldNovoEnderecoCliente;
    private javax.swing.JTextField jTextFieldNovobairro;
    private javax.swing.JTextField jTextFieldNovocidade;
    private javax.swing.JTextField jTextFieldNovocomplemento;
    private javax.swing.JTextField jTextFieldNovoemail;
    private javax.swing.JTextField jTextFieldNovonumeroEndereco;
    private javax.swing.JTextField jTextFieldNovouf;
    private javax.swing.JTextField jTextFieldNumeroEndereco;
    private javax.swing.JTextField jTextFieldOperacaoNovoNomeRazaoSocial;
    private javax.swing.JTextField jTextFieldSexo;
    private javax.swing.JTextField jTextFieldTelefone;
    private javax.swing.JTextField jTextFieldUF;
    // End of variables declaration//GEN-END:variables

}
