/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sla.clientes.forms;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import sla.clientes.ClientePessoaFisica;
import sla.clientes.ClientePessoaJuridica;
import sla.clientes.NegocioCliente;


public class FormCadastrarCliente extends javax.swing.JFrame implements ActionListener {

    public MaskFormatter mascaraTelefone;
    public MaskFormatter mascaraCPF;
    public MaskFormatter mascaraCNPJ;
    public MaskFormatter mascaracep;

    /**
     * Creates new form FormCadastrarCliente2
     */
    public FormCadastrarCliente() {
        initComponents();
        setTitle("CADASTRO DE CLIENTES");
        // jButtonOperacao.setBounds(377, 539, 100, 66);
        // JOptionPane.showMessageDialog(null, jButtonOperacao.getBounds());
        //   jTextFieldnomeCliente.setBounds(111, 116, 450,28);

        try {
            jRadioButtonPF.setSelected(true);

            mascaraTelefone = new MaskFormatter("(##)#####-####");
            mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraCNPJ = new MaskFormatter("##.###.###/####-##");
            mascaracep = new MaskFormatter("##.###-###");

            mascaraCPF.install(jFormattedTextFieldOperacaoCpfCnpj);
            jRadioButtonPF.addActionListener(this);
            jRadioButtonPJ.addActionListener(this);

        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTipoPessoa = new javax.swing.ButtonGroup();
        buttonGroupSexo = new javax.swing.ButtonGroup();
        jLabelcidade = new javax.swing.JLabel();
        jLabel1UF = new javax.swing.JLabel();
        jTextFielduf = new javax.swing.JTextField();
        jLabelEXUF = new javax.swing.JLabel();
        jTextFieldemail = new javax.swing.JTextField();
        jLabelemail = new javax.swing.JLabel();
        jButtonOperacao = new javax.swing.JButton();
        jLabelOperacaoCpfCNPJ = new javax.swing.JLabel();
        jLabelOperacaoNomeRazaoSocial = new javax.swing.JLabel();
        jFormattedTextFieldcepCliente = new javax.swing.JFormattedTextField();
        jTextFieldOperacaoNomeRazaoSocial = new javax.swing.JTextField();
        jRadioButtonPF = new javax.swing.JRadioButton();
        jLabeltelefoneCliente = new javax.swing.JLabel();
        jRadioButtonPJ = new javax.swing.JRadioButton();
        jFormattedTextFieldtelefoneCliente = new javax.swing.JFormattedTextField();
        jRadioButtonSexoMasculino = new javax.swing.JRadioButton();
        jLabelenderecoCliente = new javax.swing.JLabel();
        jRadioButtonSexoFeminino = new javax.swing.JRadioButton();
        jTextFieldEnderecoCliente = new javax.swing.JTextField();
        jLabelSexoCliente = new javax.swing.JLabel();
        jLabelcepCliente = new javax.swing.JLabel();
        jTextFieldnumeroEndereco = new javax.swing.JTextField();
        jLabelnumeroEndereco = new javax.swing.JLabel();
        jTextFieldcomplemento = new javax.swing.JTextField();
        jLabelcomplemento = new javax.swing.JLabel();
        jTextFieldbairro = new javax.swing.JTextField();
        jLabelbairro = new javax.swing.JLabel();
        jTextFieldcidade = new javax.swing.JTextField();
        jFormattedTextFieldOperacaoCpfCnpj = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelcidade.setText("CIDADE");

        jLabel1UF.setText("UF");

        jTextFielduf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldufKeyTyped(evt);
            }
        });

        jLabelEXUF.setText("Ex: SP");

        jLabelemail.setText("EMAIL");

        jButtonOperacao.setText("CADASTRAR");
        jButtonOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOperacaoActionPerformed(evt);
            }
        });

        jLabelOperacaoCpfCNPJ.setText("CPF");

        jLabelOperacaoNomeRazaoSocial.setText("NOME");

        try {
            jFormattedTextFieldcepCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        buttonGroupTipoPessoa.add(jRadioButtonPF);
        jRadioButtonPF.setText("PESSOA FÍSICA");

        jLabeltelefoneCliente.setText("TELEFONE");

        buttonGroupTipoPessoa.add(jRadioButtonPJ);
        jRadioButtonPJ.setText("PESSOA JURÍDICA");

        try {
            jFormattedTextFieldtelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#.####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldtelefoneCliente.setText("(  )9.    -    ");

        buttonGroupSexo.add(jRadioButtonSexoMasculino);
        jRadioButtonSexoMasculino.setSelected(true);
        jRadioButtonSexoMasculino.setText("MASCULINO");

        jLabelenderecoCliente.setText("ENDEREÇO");

        buttonGroupSexo.add(jRadioButtonSexoFeminino);
        jRadioButtonSexoFeminino.setText("FEMININO");

        jLabelSexoCliente.setText("SEXO");

        jLabelcepCliente.setText("CEP");

        jLabelnumeroEndereco.setText("NUMERO");

        jLabelcomplemento.setText("COMPLEMENTO");

        jLabelbairro.setText("BAIRRO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelcepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelenderecoCliente)
                                            .addComponent(jLabeltelefoneCliente)
                                            .addComponent(jLabelbairro)
                                            .addComponent(jLabelemail)
                                            .addComponent(jLabelnumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelSexoCliente)
                                            .addComponent(jLabel1UF)
                                            .addComponent(jLabelcomplemento, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelOperacaoNomeRazaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldemail, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                                    .addComponent(jTextFieldEnderecoCliente)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextFieldcomplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                .addComponent(jTextFieldnumeroEndereco)
                                                .addComponent(jTextFieldbairro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                .addComponent(jTextFieldcidade, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jFormattedTextFieldtelefoneCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jFormattedTextFieldcepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFielduf, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelEXUF))
                                            .addComponent(jTextFieldOperacaoNomeRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jFormattedTextFieldOperacaoCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonSexoMasculino)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonSexoFeminino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonOperacao)
                                        .addGap(117, 117, 117))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(jRadioButtonPF)
                                .addGap(53, 53, 53)
                                .addComponent(jRadioButtonPJ)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(73, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOperacaoCpfCNPJ)
                            .addComponent(jLabelcidade))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPF)
                    .addComponent(jRadioButtonPJ))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOperacaoCpfCNPJ)
                    .addComponent(jFormattedTextFieldOperacaoCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldOperacaoNomeRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOperacaoNomeRazaoSocial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldtelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeltelefoneCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldcepCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcepCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelenderecoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelnumeroEndereco)
                    .addComponent(jTextFieldnumeroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldcomplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelcomplemento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelbairro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelcidade)
                    .addComponent(jTextFieldcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFielduf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1UF)
                    .addComponent(jLabelEXUF))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelemail)
                            .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonSexoMasculino)
                            .addComponent(jRadioButtonSexoFeminino)
                            .addComponent(jLabelSexoCliente))
                        .addContainerGap(111, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOperacaoActionPerformed
        NegocioCliente cliente = new NegocioCliente();

        try {
            if (jLabelOperacaoCpfCNPJ.getText().equals("CPF")) {
                ClientePessoaFisica PF = new ClientePessoaFisica();
                PF.setBairro(jTextFieldbairro.getText());
                PF.setCep(jFormattedTextFieldcepCliente.getText());
                PF.setCidade(jTextFieldcidade.getText());
                PF.setCli_Cpf(jFormattedTextFieldOperacaoCpfCnpj.getText());
                PF.setComplemento(jTextFieldcomplemento.getText());
                PF.setEmail(jTextFieldemail.getText());
                PF.setEstado(jTextFielduf.getText());
                PF.setLogradouro(jTextFieldEnderecoCliente.getText());
                PF.setNome(jTextFieldOperacaoNomeRazaoSocial.getText());
                PF.setNumeroLogradouro(jTextFieldnumeroEndereco.getText());
                PF.setTelefone(jFormattedTextFieldtelefoneCliente.getText());
                if (jRadioButtonSexoMasculino.isSelected()) {
                    PF.setSexo("M");
                }else  if (jRadioButtonSexoFeminino.isSelected()) {
                    PF.setSexo("F");
                }
                cliente.cadastrarClientePF(PF);
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso.");
                jFormattedTextFieldOperacaoCpfCnpj.setText("");
                jTextFieldOperacaoNomeRazaoSocial.setText("");
                jFormattedTextFieldtelefoneCliente.setText("");
                jFormattedTextFieldcepCliente.setText("");
                jTextFieldEnderecoCliente.setText("");
                jTextFieldnumeroEndereco.setText("");
                jTextFieldcomplemento.setText("");
                jTextFieldbairro.setText("");
                jTextFieldcidade.setText("");
                jTextFielduf.setText("");
                jTextFieldemail.setText("");
                jRadioButtonSexoMasculino.setSelected(false);
                jRadioButtonSexoFeminino.setSelected(false);

            }

            if (jLabelOperacaoCpfCNPJ.getText().equals("CNPJ")) {
                ClientePessoaJuridica PJ = new ClientePessoaJuridica();
                PJ.setBairro(jTextFieldbairro.getText());
                PJ.setCep(jFormattedTextFieldcepCliente.getText());
                PJ.setCidade(jTextFieldcidade.getText());
                PJ.setCli_Cnpj(jFormattedTextFieldOperacaoCpfCnpj.getText());
                PJ.setComplemento(jTextFieldcomplemento.getText());
                PJ.setEmail(jTextFieldemail.getText());
                PJ.setEstado(jTextFielduf.getText());
                PJ.setLogradouro(jTextFieldEnderecoCliente.getText());
                PJ.setRazaoSocial(jTextFieldOperacaoNomeRazaoSocial.getText());
                PJ.setNumeroLogradouro(jTextFieldnumeroEndereco.getText());
                PJ.setTelefone(jFormattedTextFieldtelefoneCliente.getText());
                cliente.cadastrarClientePJ(PJ);
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso.");
                jFormattedTextFieldOperacaoCpfCnpj.setText("");
                jTextFieldOperacaoNomeRazaoSocial.setText("");
                jFormattedTextFieldtelefoneCliente.setText("");
                jFormattedTextFieldcepCliente.setText("");
                jTextFieldEnderecoCliente.setText("");
                jTextFieldnumeroEndereco.setText("");
                jTextFieldcomplemento.setText("");
                jTextFieldbairro.setText("");
                jTextFieldcidade.setText("");
                jTextFielduf.setText("");
                jTextFieldemail.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }

    }//GEN-LAST:event_jButtonOperacaoActionPerformed

    private void jTextFieldufKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldufKeyTyped
      // Teste de uso de eventos para limitar o campo estado somente com caracteres e com limite de 2 caracteres para o estado.
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c)) || c == ' ') {
            evt.consume();
        }
        int numerocaracter = 2;

        if (jTextFielduf.getText().length() >= numerocaracter) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldufKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new FormCadastrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupSexo;
    private javax.swing.ButtonGroup buttonGroupTipoPessoa;
    private javax.swing.JButton jButtonOperacao;
    private javax.swing.JFormattedTextField jFormattedTextFieldOperacaoCpfCnpj;
    private javax.swing.JFormattedTextField jFormattedTextFieldcepCliente;
    private javax.swing.JFormattedTextField jFormattedTextFieldtelefoneCliente;
    private javax.swing.JLabel jLabel1UF;
    private javax.swing.JLabel jLabelEXUF;
    private javax.swing.JLabel jLabelOperacaoCpfCNPJ;
    private javax.swing.JLabel jLabelOperacaoNomeRazaoSocial;
    private javax.swing.JLabel jLabelSexoCliente;
    private javax.swing.JLabel jLabelbairro;
    private javax.swing.JLabel jLabelcepCliente;
    private javax.swing.JLabel jLabelcidade;
    private javax.swing.JLabel jLabelcomplemento;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelenderecoCliente;
    private javax.swing.JLabel jLabelnumeroEndereco;
    private javax.swing.JLabel jLabeltelefoneCliente;
    private javax.swing.JRadioButton jRadioButtonPF;
    private javax.swing.JRadioButton jRadioButtonPJ;
    private javax.swing.JRadioButton jRadioButtonSexoFeminino;
    private javax.swing.JRadioButton jRadioButtonSexoMasculino;
    private javax.swing.JTextField jTextFieldEnderecoCliente;
    private javax.swing.JTextField jTextFieldOperacaoNomeRazaoSocial;
    private javax.swing.JTextField jTextFieldbairro;
    private javax.swing.JTextField jTextFieldcidade;
    private javax.swing.JTextField jTextFieldcomplemento;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldnumeroEndereco;
    private javax.swing.JTextField jTextFielduf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        if (ae.getSource() == jRadioButtonPF) {
            jRadioButtonSexoMasculino.setVisible(true);
            jRadioButtonSexoFeminino.setVisible(true);
            jLabelSexoCliente.setVisible(true);
            if (jLabelOperacaoCpfCNPJ.getText().equals("CNPJ")) {
                jLabelOperacaoCpfCNPJ.setText("CPF");
                jLabelOperacaoNomeRazaoSocial.setText("NOME");
                mascaraCNPJ.uninstall();
                mascaraCPF.install(jFormattedTextFieldOperacaoCpfCnpj);

            }

        }

        if (ae.getSource() == jRadioButtonPJ) {
            jRadioButtonSexoMasculino.setVisible(false);
            jRadioButtonSexoFeminino.setVisible(false);
            jLabelSexoCliente.setVisible(false);

            if (jLabelOperacaoCpfCNPJ.getText().equals("CPF")) {
                jLabelOperacaoCpfCNPJ.setText("CNPJ");
                jLabelOperacaoNomeRazaoSocial.setText("RAZÃO SOCIAL");
                mascaraCPF.uninstall();
                mascaraCNPJ.install(jFormattedTextFieldOperacaoCpfCnpj);

            }
        }

    }
}
